# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: stross <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/02/19 15:50:24 by stross            #+#    #+#              #
#    Updated: 2020/02/25 17:35:04 by sdoughnu         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		=   asm

CC			=	gcc
FLAGS		=	-Wall -Wextra -Werror -g
D_FLAGS		=	-g

DELTA		=	$$(echo "$$(tput cols)-47"|bc)

LIBFT_DIR	=	../libft/
LIBFT_LIB	=	$(LIBFT_DIR)libft.a
LIBFT_INC	=	$(LIBFT_DIR)libft.h

LIBS		=

SRC_DIR		=	./
INC_DIR		=	../includes/
OBJ_DIR		=	.objs/

SRC_BASE    =   asm.c               \
                assembly_2.c        \
                assembly.c          \
                check_commands_2.c  \
                check_commands_3.c  \
                check_commands.c    \
                create_file.c       \
                errors_three.c      \
                errors_two.c        \
                errors.c            \
                free.c              \
                list_functions.c    \
                parse.c             \
                utils_write.c       \
                utils.c             \
                utils2.c            \
                validation_utils.c  \
                validation.c        \
                write_arguments.c   \
                write_commands.c    \
				more_validation.c	\
				validate_labels.c	\
				norminette.c		\
				norminette2.c

SRCS		=	$(addprefix $(SRC_DIR), $(SRC_BASE))
OBJS		=	$(addprefix $(OBJ_DIR), $(SRC_BASE:.c=.o))
NB			=	$(words $(SRC_BASE))
INDEX		=	0

all :
	@make -j $(NAME)

$(NAME):		$(LIBFT_LIB) $(OBJ_DIR) $(OBJS)
	@$(CC) $(OBJS) -o $(NAME)   \
		-I $(INC_DIR)           \
		-I $(LIBFT_INC)         \
		$(LIBS)                 \
		$(LIBFT_LIB)            \
		$(FLAGS) $(D_FLAGS)
	@strip -x $@
	@printf "\r\033[48;5;15;38;5;25m✅ MAKE $(NAME)\033[0m\033[K\n"
	@cp asm ../asm

$(LIBFT_LIB):
	@make -C $(LIBFT_DIR)

$(OBJ_DIR) :
	@mkdir -p $(OBJ_DIR)
	@mkdir -p $(dir $(OBJS))

$(OBJ_DIR)%.o :	$(SRC_DIR)%.c | $(OBJ_DIR)
	@$(eval DONE=$(shell echo $$(($(INDEX)*20/$(NB)))))
	@$(eval PERCENT=$(shell echo $$(($(INDEX)*100/$(NB)))))
	@$(eval COLOR=$(shell echo $$(($(PERCENT)%35+196))))
	@$(eval TO_DO=$(shell echo $$((20-$(INDEX)*20/$(NB)))))
	@printf "\r\033[38;5;11m⌛ MAKE %10.10s : %2d%% \033[48;5;%dm%*s\033[0m%*s\033[48;5;255m \033[0m \033[38;5;11m %*.*s\033[0m\033[K" $(NAME) $(PERCENT) $(COLOR) $(DONE) "" $(TO_DO) "" $(DELTA) $(DELTA) "$@"
	@$(CC) $(FLAGS) $(D_FLAGS) -MMD -c $< -o $@\
		-I $(INC_DIR)\
		-I $(LIBFT_INC)
	@$(eval INDEX=$(shell echo $$(($(INDEX)+1))))

clean:
	@rm -rf $(OBJ_DIR)
	@printf "\r\033[38;5;202m✖ clean $(NAME)\033[0m\033[K\n"

fclean:			clean
	@rm -f $(NAME)
	@rm -f ../asm
	@printf "\r\033[38;5;196m❌ fclean $(NAME)\033[0m\033[K\n"

re:				fclean all

-include $(OBJS:.o=.d)
